version: "3.8"

services:

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: {{APP_SLUG}}
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local