version: "3.8"

services:

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5001:5432"  # map host's 127.0.0.1:5001 to default psql port inside container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: {{APP_SLUG}}
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: "redis:alpine"
    ports:
      - "5002:6379"   # map host's 127.0.0.1:5002 to default redis port inside container

volumes:
  pgdata:
    driver: local