version: "3.8"

services:

  web:
    build: .
    entrypoint: ["flask"]
    command: ["run", "--host=0.0.0.0", "--reload"]
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:local_pass@db/flask-boilerplate
    volumes:
      - .:/flask-app
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: flask-boilerplate
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local