version: "3.8"

services:

  web:
    build: .
    entrypoint: ["flask"]
    command: ["run", "--host=0.0.0.0", "--reload"]
    ports:
      - "8000:80"  # map port 8000 on host's localhost to port 80 inside container
    env_file: .dockerenv
    volumes:
      - .:/flask-app
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432"  # exposes postgresql://db:5432 within containers https://docs.docker.com/compose/networking/
    env_file: .dockerenv
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local